version: '3'
# docker-compose.yml
services:
  # MySQL
  db: 
    # image: mysql:5.7.29
    image: mysql:8.0
    container_name: mysql_host
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test_database
        MYSQL_USER: docker
        MYSQL_PASSWORD: docker
        TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
        - ./services/db/data:/var/lib/mysql
    ports:
        - 3306:3306