version: '3'
services:
    db:
        image: mariadb:10.11.3
        volumes:
          - ./db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_PASSWORD: mysql
          MYSQL_DATABASE: database
          MYSQL_USER: mysql
          TZ: 'Asia/Tokyo'